### ISSUE TITLE
详情页的上一篇和下一篇按钮，需要与标题的线对齐

### ISSUE THREAD

**Issue by LiChunyu77** [ccnu-lab/ccnu-lab.github.io#30]
![Image](https://user-images.githubusercontent.com/101395055/221495841-2f2626ff-e644-4ec3-999f-94c784e5a3a5.png)

**Comment by tninenine** [comment]
在29号卡一并修复

**Comment by tninenine** [comment]
https://github.com/orgs/ccnu-lab/projects/1?pane=issue&itemId=21481529
